# Generated by Django 3.0.7 on 2020-06-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lizt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lizt_item', models.CharField(default='no items', max_length=100)),
                ('quantity', models.CharField(default='0', max_length=10)),
                ('lizt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lizt.Lizt')),
            ],
        ),
    ]
